function flag = segment_overlap(start,stop,starts,stops)
% flag = segment_overlap(start,stop,starts,stops)  

flag = ((start >= starts) & (start<=stops)) | ...
       ((stop >= starts) & (stop<=stops)) | ...
       ((start <=starts) & (stop>=stops)) | ...
       ((start >=starts) & (stop<=stops)) ;
  