function fields = default_gene_field_names()
% fields = default_gene_field_names()

fields={'utr5_exons', 'transcripts', 'utr3_exons', 'utr_5prime', ...
        'utr_3prime', 'tis', 'tss', 'cdsStop', 'cleave', 'strain', ...
        'cds_exons', 'exons', 'transcript_origin', 'transcript_valid', ...
        'transcript_coding', 'transcript_complete', ...
        'transcript_explain', 'transcript_score', ...
        'transcript_weights', 'transcript_type' } ;
